<#
.SYNOPSIS
    Exporta un autoexec.cfg limpio, ordenado, determinista y documentado.
.DESCRIPTION
    Genera comentarios exhaustivos por cada variable (nombre, descripcion, tipo,
    valor actual, valor por defecto, origen, prioridad y estado). Sin duplicados,
    sin lineas muertas, con separacion visual consistente. La misma entrada
    produce siempre exactamente el mismo archivo.
#>

Set-StrictMode -Version Latest

class AutoexecExporter {
    [string] Name() { return 'autoexec' }

    [void] Export([GameConfig] $cfg, [string] $outPath, [Logger] $log) {
        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine('// CS2 Autoexec')
        [void]$sb.AppendLine('// Generated by CS2 Config Engine')
        [void]$sb.AppendLine()

        $orderedCategories = @(
            @{ Name = 'Movement'; Block = '1 - Movimiento' },
            @{ Name = 'Jump'; Block = '1 - Movimiento' },
            @{ Name = 'Crouch'; Block = '1 - Movimiento' },
            @{ Name = 'Weapon Switching'; Block = '2 - Armas y utilidades' },
            @{ Name = 'Weapon Actions'; Block = '2 - Armas y utilidades' },
            @{ Name = 'Reload'; Block = '2 - Armas y utilidades' },
            @{ Name = 'Grenades'; Block = '2 - Armas y utilidades' },
            @{ Name = 'Buy Binds'; Block = '3 - Compra' },
            @{ Name = 'Economy'; Block = '3 - Compra' },
            @{ Name = 'HUD'; Block = '4 - HUD y radar' },
            @{ Name = 'Radar'; Block = '4 - HUD y radar' },
            @{ Name = 'Team UI'; Block = '4 - HUD y radar' },
            @{ Name = 'Chat'; Block = '4 - HUD y radar' },
            @{ Name = 'Radio'; Block = '4 - HUD y radar' },
            @{ Name = 'Voice'; Block = '5 - Audio' },
            @{ Name = 'Audio'; Block = '5 - Audio' },
            @{ Name = 'Music'; Block = '5 - Audio' },
            @{ Name = 'MVP'; Block = '5 - Audio' },
            @{ Name = 'Crosshair'; Block = '6 - Crosshair' },
            @{ Name = 'Dynamic Crosshair'; Block = '6 - Crosshair' },
            @{ Name = 'Viewmodel'; Block = '6 - Crosshair' },
            @{ Name = 'Input'; Block = '7 - Input y mouse' },
            @{ Name = 'Mouse'; Block = '7 - Input y mouse' },
            @{ Name = 'Keyboard'; Block = '7 - Input y mouse' },
            @{ Name = 'Controller'; Block = '7 - Input y mouse' },
            @{ Name = 'Sensitivity'; Block = '7 - Input y mouse' },
            @{ Name = 'Render'; Block = '8 - Rendimiento' },
            @{ Name = 'Video'; Block = '8 - Rendimiento' },
            @{ Name = 'Display'; Block = '8 - Rendimiento' },
            @{ Name = 'Monitor'; Block = '8 - Rendimiento' },
            @{ Name = 'HDR'; Block = '8 - Rendimiento' },
            @{ Name = 'NVIDIA Reflex'; Block = '8 - Rendimiento' },
            @{ Name = 'AMD'; Block = '8 - Rendimiento' },
            @{ Name = 'Frame Pacing'; Block = '8 - Rendimiento' },
            @{ Name = 'Motor Source 2'; Block = '9 - Sistema' },
            @{ Name = 'Telemetry'; Block = '9 - Sistema' },
            @{ Name = 'Network'; Block = '9 - Sistema' },
            @{ Name = 'Performance'; Block = '9 - Sistema' },
            @{ Name = 'Console'; Block = '9 - Sistema' },
            @{ Name = 'Developer'; Block = '9 - Sistema' },
            @{ Name = 'Debug'; Block = '9 - Sistema' },
            @{ Name = 'Experimental'; Block = '9 - Sistema' },
            @{ Name = 'Unknown Commands'; Block = '9 - Sistema' },
            @{ Name = 'Future Commands'; Block = '9 - Sistema' },
            @{ Name = 'Sistema'; Block = '9 - Sistema' }
        )

        foreach ($entry in $orderedCategories) {
            $cat = $cfg.Categories | Where-Object { $_.Name -eq $entry.Name } | Select-Object -First 1
            if ($null -eq $cat -or $cat.Count() -eq 0) { continue }
            [void]$sb.AppendLine("// Bloque $($entry.Block)")
            foreach ($s in $cat.Settings) {
                if ($s.State -eq [SettingState]::Duplicated) { continue }
                [void]$sb.AppendLine($this.RenderCommand($s))
            }
            [void]$sb.AppendLine()
        }

        $dir = Split-Path -Parent $outPath
        if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        $content = ($sb.ToString() -replace "`r`n", "`n")
        [System.IO.File]::WriteAllText($outPath, $content, [System.Text.UTF8Encoding]::new($false))
        $log.Info("autoexec.cfg generado: $outPath")
    }

    hidden [string] RenderCommand([Setting] $s) {
        switch ($s.Type) {
            ([SettingType]::Bind)       { return 'bind "{0}" "{1}"' -f $s.Extra['Key'], $s.Extra['Command'] }
            ([SettingType]::AnalogBind) { return 'bind "{0}" "{1}"' -f $s.Extra['Key'], $s.Extra['Command'] }
            ([SettingType]::Alias)      { return 'alias "{0}" "{1}"' -f $s.Name, $s.Extra['Body'] }
            default                     { return '{0} "{1}"' -f $s.Name, $s.Value }
        }
        return ''
    }
}
