<#
.SYNOPSIS
    Exporta un autoexec.cfg limpio, ordenado, determinista y ejecutable.
.DESCRIPTION
    Recorre los bloques declarados en CategoryMap (unica fuente del
    agrupamiento) para que ninguna categoria pueda quedarse fuera del archivo.
    Cada bloque imprime su encabezado UNA sola vez, aunque agrupe varias
    categorias.

    Politica de emision, coherente con "nada se descarta jamas":
      - Los ajustes sanos se emiten como comandos activos.
      - Los duplicados, obsoletos, invalidos y los no reconocidos (P48) se
        emiten COMENTADOS con el motivo. Se conserva la informacion y el
        archivo sigue siendo ejecutable sin que la consola de CS2 escupa
        errores linea por linea.
      - P49 (posibles convars futuras) SI se emite activo: tiene forma de
        convar valida y lo mas probable es que sea real, solo que el catalogo
        aun no la clasifica.

    Sin marcas de tiempo: la misma entrada produce siempre el mismo archivo.
#>

Set-StrictMode -Version Latest

class AutoexecExporter {
    [string] Name() { return 'autoexec' }

    [void] Export([GameConfig] $cfg, [string] $outPath, [Logger] $log) {
        # Indice por codigo para no recorrer la lista una vez por bloque.
        $byCode = [System.Collections.Generic.Dictionary[string, ConfigCategory]]::new(
            [System.StringComparer]::OrdinalIgnoreCase)
        foreach ($cat in $cfg.Categories) {
            if (-not $byCode.ContainsKey($cat.Code)) { $byCode[$cat.Code] = $cat }
        }

        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine('// CS2 Autoexec')
        [void]$sb.AppendLine('// Generated by CS2 Config Engine')
        [void]$sb.AppendLine('// Las lineas comentadas se conservan por trazabilidad; el motivo va al final.')
        [void]$sb.AppendLine()

        $emitted  = 0
        $disabled = 0

        foreach ($block in [CategoryMap]::AllBlocks()) {
            $codes = [CategoryMap]::CodesInBlock($block)

            # Encabezado del bloque solo si alguna de sus categorias trae algo.
            $hasContent = $false
            foreach ($code in $codes) {
                if ($byCode.ContainsKey($code) -and $byCode[$code].Count() -gt 0) { $hasContent = $true; break }
            }
            if (-not $hasContent) { continue }

            [void]$sb.AppendLine("// Bloque $block")
            foreach ($code in $codes) {
                if (-not $byCode.ContainsKey($code)) { continue }
                $cat = $byCode[$code]
                if ($cat.Count() -eq 0) { continue }
                foreach ($s in $cat.Settings) {
                    $reason = $this.DisableReason($s, $cat.Code)
                    if ($reason) {
                        [void]$sb.AppendLine(('// {0}   // {1}' -f $this.RenderCommand($s), $reason))
                        $disabled++
                    } else {
                        [void]$sb.AppendLine($this.RenderCommand($s))
                        $emitted++
                    }
                }
            }
            [void]$sb.AppendLine()
        }

        # Aviso si el catalogo y el mapa de bloques se desincronizan.
        foreach ($problem in [CategoryMap]::AssertComplete()) {
            $log.Warn("CategoryMap incompleto: $problem")
        }

        $dir = Split-Path -Parent $outPath
        if ($dir -and -not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        $content = ($sb.ToString() -replace "`r`n", "`n")
        [System.IO.File]::WriteAllText($outPath, $content, [System.Text.UTF8Encoding]::new($false))
        $log.Info("autoexec.cfg generado: $outPath ($emitted activos, $disabled comentados)")
    }

    <#
        Motivo por el que un ajuste no debe ejecutarse, o '' si es sano.
        Se comenta solo lo que romperia el exec o lo que ya no existe; nunca se
        omite del archivo.

        La categoria llega como parametro en lugar de leerse de $s.CategoryCode:
        manda la categoria que realmente contiene al ajuste, de modo que un
        Setting construido a mano (tests, fixtures) no se desactive por llevar
        el codigo P48 que trae el constructor por defecto.
    #>
    hidden [string] DisableReason([Setting] $s, [string] $categoryCode) {
        switch ($s.State) {
            ([SettingState]::Duplicated) {
                $origin = if ($s.Metadata.SourceFile) { Split-Path -Leaf $s.Metadata.SourceFile } else { 'origen desconocido' }
                return "duplicado ($origin linea $($s.Metadata.SourceLine)); prevalece la config viva de mayor prioridad"
            }
            ([SettingState]::Obsolete) { return 'obsoleta: eliminada en versiones recientes de CS2' }
            ([SettingState]::Invalid)  { return 'invalida: nombre de variable no utilizable' }
        }
        if ($categoryCode -eq 'P48') { return 'no reconocido como comando de consola' }
        return ''
    }

    hidden [string] RenderCommand([Setting] $s) {
        switch ($s.Type) {
            ([SettingType]::Bind)       { return 'bind "{0}" "{1}"' -f $s.Extra['Key'], $s.Extra['Command'] }
            ([SettingType]::AnalogBind) { return 'bind "{0}" "{1}"' -f $s.Extra['Key'], $s.Extra['Command'] }
            ([SettingType]::Alias)      { return 'alias "{0}" "{1}"' -f $s.Name, $s.Extra['Body'] }
        }
        return '{0} "{1}"' -f $s.Name, $s.Value
    }
}
